# Generated by Django 5.1.4 on 2025-01-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="github_link",
            new_name="link",
        ),
        migrations.RemoveField(
            model_name="project",
            name="live_link",
        ),
        migrations.AddField(
            model_name="project",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="project_images/"),
        ),
        migrations.AlterField(
            model_name="project",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
