# Generated by Django 5.1.4 on 2025-01-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0002_rename_github_link_project_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(
                default="project_images/img.jpg", upload_to="project_images/"
            ),
        ),
    ]
